/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CreateIndexImport } from './routes/create/index'
import { Route as ViewNoteIdImport } from './routes/view/$noteId'
import { Route as ShareNoteIdImport } from './routes/share/$noteId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CreateIndexRoute = CreateIndexImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRoute,
} as any)

const ViewNoteIdRoute = ViewNoteIdImport.update({
  id: '/view/$noteId',
  path: '/view/$noteId',
  getParentRoute: () => rootRoute,
} as any)

const ShareNoteIdRoute = ShareNoteIdImport.update({
  id: '/share/$noteId',
  path: '/share/$noteId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/share/$noteId': {
      id: '/share/$noteId'
      path: '/share/$noteId'
      fullPath: '/share/$noteId'
      preLoaderRoute: typeof ShareNoteIdImport
      parentRoute: typeof rootRoute
    }
    '/view/$noteId': {
      id: '/view/$noteId'
      path: '/view/$noteId'
      fullPath: '/view/$noteId'
      preLoaderRoute: typeof ViewNoteIdImport
      parentRoute: typeof rootRoute
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/share/$noteId': typeof ShareNoteIdRoute
  '/view/$noteId': typeof ViewNoteIdRoute
  '/create': typeof CreateIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/share/$noteId': typeof ShareNoteIdRoute
  '/view/$noteId': typeof ViewNoteIdRoute
  '/create': typeof CreateIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/share/$noteId': typeof ShareNoteIdRoute
  '/view/$noteId': typeof ViewNoteIdRoute
  '/create/': typeof CreateIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/share/$noteId' | '/view/$noteId' | '/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/share/$noteId' | '/view/$noteId' | '/create'
  id: '__root__' | '/' | '/share/$noteId' | '/view/$noteId' | '/create/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShareNoteIdRoute: typeof ShareNoteIdRoute
  ViewNoteIdRoute: typeof ViewNoteIdRoute
  CreateIndexRoute: typeof CreateIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShareNoteIdRoute: ShareNoteIdRoute,
  ViewNoteIdRoute: ViewNoteIdRoute,
  CreateIndexRoute: CreateIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/share/$noteId",
        "/view/$noteId",
        "/create/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/share/$noteId": {
      "filePath": "share/$noteId.tsx"
    },
    "/view/$noteId": {
      "filePath": "view/$noteId.tsx"
    },
    "/create/": {
      "filePath": "create/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
